'use client'

import { motion } from 'framer-motion'
import Link from 'next/link'
import Container from '@/components/ui/Container'
import Button from '@/components/ui/Button'
import HeroCarousel from './HeroCarousel'
import type { HomeStory } from '@/lib/data/homepage-stories'

interface HomePageClientProps {
  readonly featuredStories: HomeStory[]
}

export default function HomePageClient({
  featuredStories,
}: HomePageClientProps) {
  return (
    <>
      {/* Introduction Section */}
      <section className="relative py-12 md:py-16">
        <Container maxWidth="content" className="relative">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="text-center space-y-4"
          >
            <h1 className="font-display text-4xl md:text-5xl text-text-primary dark:text-dark-text-primary leading-tight">
              A Safe Space for Visibility Moments
            </h1>
            <p className="text-lg md:text-xl text-text-secondary dark:text-dark-text-secondary max-w-2xl mx-auto font-serif leading-relaxed">
              Share your mental health story anonymously. Real moments of courage, curated with compassion. No algorithms. No judgment. Just human connection.
            </p>
          </motion.div>
        </Container>
      </section>

      {/* Hero Carousel Section */}
      <section className="relative pt-4 pb-12 md:pb-20">
        <HeroCarousel stories={featuredStories} />
      </section>

      {/* What is this space Section */}
      <section className="py-16 md:py-24 relative">
        {/* Glassmorphic background */}
        <div className="absolute inset-0 bg-white/30 dark:bg-white/5 backdrop-blur-xl" />
        <div className="absolute inset-0 bg-gradient-to-br from-rose-50/50 via-transparent to-amber-50/50 dark:from-rose-900/10 dark:via-transparent dark:to-amber-900/10" />

        <Container maxWidth="wide" className="relative">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="font-display text-3xl md:text-4xl text-text-primary dark:text-dark-text-primary mb-4">
              What is this space?
            </h2>
            <p className="font-serif text-lg text-text-secondary dark:text-dark-text-secondary max-w-3xl mx-auto leading-relaxed">
              A safe place for even those small, profound moments of courage. Going to the grocery store after weeks of anxiety. Speaking up in a meeting. Making eye contact. These moments might seem ordinary, but they&apos;re acts of visibility, witnessed with compassion, never judgment.
            </p>
          </motion.div>

          {/* Values grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-6">
            {[
              { icon: '🔒', title: 'Privacy-First', desc: 'No tracking. No data collection beyond necessity.' },
              { icon: '👥', title: 'Human-Centric', desc: 'Real people review every story with care and compassion.' },
              { icon: '🚫', title: 'No AI', desc: 'Stories never analyzed, moderated, or generated by algorithms.' },
              { icon: '📵', title: 'No Ads', desc: 'Ad-free space funded by donations and community support.' },
              { icon: '⚖️', title: 'No Algorithm', desc: 'Chronological, not algorithmic. No engagement manipulation.' },
              { icon: '💰', title: 'No Data Monetization', desc: 'Your data never sold, shared, or profited from.' },
            ].map((value, idx) => (
              <motion.div
                key={value.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: idx * 0.08 }}
                viewport={{ once: true }}
              >
                <div className="group relative h-full p-6 rounded-xl border border-white/20 dark:border-white/10 hover:border-white/40 dark:hover:border-white/20 bg-white/20 dark:bg-white/5 backdrop-blur-xl hover:bg-white/30 dark:hover:bg-white/10 transition-all duration-300">
                  <div className="text-3xl mb-3 group-hover:scale-110 transition-transform duration-300">
                    {value.icon}
                  </div>
                  <h3 className="font-display text-lg text-text-primary dark:text-dark-text-primary mb-2">
                    {value.title}
                  </h3>
                  <p className="text-sm text-text-secondary dark:text-dark-text-secondary">
                    {value.desc}
                  </p>
                </div>
              </motion.div>
            ))}
          </div>
        </Container>
      </section>

      {/* How It Works Section */}
      <section className="py-16 md:py-24 relative">
        <Container maxWidth="wide">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="font-display text-3xl md:text-4xl text-text-primary dark:text-dark-text-primary mb-16 text-center"
          >
            How it works
          </motion.h2>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {[
              {
                icon: '📝',
                title: 'Share your moment',
                desc: 'Write, record a voice note, or share a photo of the moment you felt visible. Be as anonymous or open as you would like.',
                delay: 0,
              },
              {
                icon: '🤝',
                title: 'Humans review carefully',
                desc: 'Every story is read with care and compassion. We ensure this remains a safe, supportive space free from judgment.',
                delay: 0.1,
              },
              {
                icon: '👁️',
                title: 'You are seen',
                desc: 'Your story is published and witnessed by others who understand. No likes, no comments, just be seen and relate to others.',
                delay: 0.2,
              },
            ].map((item, idx) => (
              <motion.div
                key={item.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: item.delay }}
                viewport={{ once: true }}
              >
                <div className="relative group h-full p-8 rounded-xl border border-white/20 dark:border-white/10 hover:border-white/40 dark:hover:border-white/20 bg-white/15 dark:bg-white/5 backdrop-blur-xl hover:bg-white/25 dark:hover:bg-white/10 transition-all duration-300">
                  <div className="text-4xl mb-4 group-hover:scale-125 transition-transform duration-300">
                    {item.icon}
                  </div>
                  <h3 className="font-display text-xl text-text-primary dark:text-dark-text-primary mb-3">
                    {item.title}
                  </h3>
                  <p className="text-text-secondary dark:text-dark-text-secondary leading-relaxed">
                    {item.desc}
                  </p>
                </div>
              </motion.div>
            ))}
          </div>
        </Container>
      </section>

      {/* Trust & Transparency Section */}
      <section className="py-16 md:py-24 relative">
        <div className="absolute inset-0 bg-white/30 dark:bg-white/5 backdrop-blur-xl" />
        <div className="absolute inset-0 bg-gradient-to-br from-rose-50/50 via-transparent to-amber-50/50 dark:from-rose-900/10 dark:via-transparent dark:to-amber-900/10" />

        <Container maxWidth="wide" className="relative">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="mb-16 text-center"
          >
            <h2 className="font-display text-3xl md:text-4xl text-text-primary dark:text-dark-text-primary mb-4">
              Your privacy is sacred
            </h2>
            <p className="font-serif text-lg text-text-secondary dark:text-dark-text-secondary max-w-2xl mx-auto">
              We believe the safest space is one where you know exactly what happens with your data.
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Privacy & Security */}
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.6 }}
              viewport={{ once: true }}
            >
              <div className="h-full p-8 rounded-xl border border-white/20 dark:border-white/10 hover:border-white/40 dark:hover:border-white/20 bg-white/20 dark:bg-white/8 backdrop-blur-xl hover:bg-white/30 dark:hover:bg-white/15 transition-all duration-300">
                <h3 className="font-display text-2xl text-text-primary dark:text-dark-text-primary mb-6">
                  🔐 How We Protect You
                </h3>
                <ul className="space-y-4 text-sm text-text-secondary dark:text-dark-text-secondary">
                  <li className="flex gap-3">
                    <span className="text-rose-500 dark:text-rose-400 font-bold flex-shrink-0">✓</span>
                    <div>
                      <strong className="text-text-primary dark:text-dark-text-primary">Privacy-first analytics.</strong> We use Vercel Web Analytics (no tracking cookies, no user profiles).
                    </div>
                  </li>
                  <li className="flex gap-3">
                    <span className="text-rose-500 dark:text-rose-400 font-bold flex-shrink-0">✓</span>
                    <div>
                      <strong className="text-text-primary dark:text-dark-text-primary">Automatic EXIF stripping.</strong> Photos are cleaned of location data and metadata.
                    </div>
                  </li>
                  <li className="flex gap-3">
                    <span className="text-rose-500 dark:text-rose-400 font-bold flex-shrink-0">✓</span>
                    <div>
                      <strong className="text-text-primary dark:text-dark-text-primary">No data sales.</strong> Your information is never shared or sold.
                    </div>
                  </li>
                </ul>
              </div>
            </motion.div>

            {/* Moderation Process */}
            <motion.div
              initial={{ opacity: 0, x: 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.6 }}
              viewport={{ once: true }}
            >
              <div className="h-full p-8 rounded-xl border border-white/20 dark:border-white/10 hover:border-white/40 dark:hover:border-white/20 bg-white/20 dark:bg-white/8 backdrop-blur-xl hover:bg-white/30 dark:hover:bg-white/15 transition-all duration-300">
                <h3 className="font-display text-2xl text-text-primary dark:text-dark-text-primary mb-6">
                  ✨ Our Moderation Promise
                </h3>
                <ul className="space-y-4 text-sm text-text-secondary dark:text-dark-text-secondary">
                  <li className="flex gap-3">
                    <span className="text-rose-500 dark:text-rose-400 font-bold flex-shrink-0">◆</span>
                    <div>
                      <strong className="text-text-primary dark:text-dark-text-primary">Real humans, no AI.</strong> Every story read by a person.
                    </div>
                  </li>
                  <li className="flex gap-3">
                    <span className="text-rose-500 dark:text-rose-400 font-bold flex-shrink-0">◆</span>
                    <div>
                      <strong className="text-text-primary dark:text-dark-text-primary">Transparent guidelines.</strong> Clear rules with thoughtful exceptions.
                    </div>
                  </li>
                  <li className="flex gap-3">
                    <span className="text-rose-500 dark:text-rose-400 font-bold flex-shrink-0">◆</span>
                    <div>
                      <strong className="text-text-primary dark:text-dark-text-primary">Typical wait: 24-48 hours.</strong> Fast enough to encourage, slow enough to care.
                    </div>
                  </li>
                </ul>
              </div>
            </motion.div>
          </div>
        </Container>
      </section>

      {/* CTA Section */}
      <section className="py-20 relative overflow-hidden">
        {/* Background layers */}
        <div className="absolute inset-0 bg-gradient-to-br from-rose-50/50 via-amber-50/30 to-rose-50/50 dark:from-rose-900/20 dark:via-amber-900/10 dark:to-rose-900/20" />
        <div className="absolute -top-40 right-0 w-96 h-96 bg-rose-200 dark:bg-rose-900 rounded-full opacity-20 dark:opacity-10 blur-3xl" />
        <div className="absolute -bottom-40 left-0 w-96 h-96 bg-amber-200 dark:bg-amber-900 rounded-full opacity-20 dark:opacity-10 blur-3xl" />

        <Container maxWidth="content" className="relative">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="text-center space-y-8"
          >
            <h2 className="font-display text-4xl md:text-5xl text-text-primary dark:text-dark-text-primary">
              Today, you showed up
            </h2>
            <p className="text-xl text-text-secondary dark:text-dark-text-secondary">
              That&apos;s worth sharing
            </p>
            <Link href="/submit">
              <Button size="lg">
                Share Your Visibility Story
              </Button>
            </Link>
          </motion.div>
        </Container>
      </section>
    </>
  )
}
